inicio
   varinicio
      A literal;
      B inteiro;
      c inteiro;
   varfim;

   escreva "Digite um nome:";
   leia A;
{nao ler}
   escreva "Digite um numero:";
   leia B;
   escreva "Seu numero vezes dois:\n";
   c <- B*2;
   escreva c;

   B <- 2;
   B <- 3.5;
   c <- B+1;
   c <- c+1;
    
   se (B<1)
   entao
     se (c <2)
     entao
       escreva "texto";
     fimse
   fimse

   escreva "programa finalizado";   

fim
